version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=https://flybackend-misty-feather-6458.fly.dev
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 